service: plataforma-atrasos-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  memorySize: 256
  timeout: 30
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DB_PORT: ${env:DB_PORT}
    JWT_SECRET: ${env:JWT_SECRET}
    STAGE: ${opt:stage, 'dev'}

  # Define CORS settings for the API Gateway
  httpApi:
    cors:
      allowedOrigins:
        - '*'  # In production you should restrict this to your specific domain
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Requested-With
        - X-Requested-By
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true
      maxAge: 86400  # 24 hours in seconds

functions:
  backend-sistema-asistencia:
    handler: src/app.handler
    name: backend-sistema-asistencia-${opt:stage, 'dev'}
    description: "Backend API for Sistema de Asistencia"
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
  output:
    file: ./serverless-output.json

package:
  patterns:
    # Include only what we need
    - 'src/**'
    - 'package.json'
    - '.env'
    - 'node_modules/whatsapp-web.js/**'
    - '!src/**/*.test.js'
    - '!src/**/__tests__/**'

    # Exclude unnecessary files and directories
    - '!node_modules/.bin/**'
    - '!node_modules/aws-sdk/**'
    - '!node_modules/cypress/**'
    - '!node_modules/@cypress/**'
    - '!node_modules/@babel/**'
    - '!node_modules/@testing-library/**'
    - '!node_modules/babel-*/**'
    - '!node_modules/jest*/**'
    - '!frontend/**'
    - '!__mocks__/**'
    - '!cypress/**'
    - '!.wwebjs_cache/**'