service: plataforma-atrasos-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  memorySize: 256
  timeout: 30
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    DB_PORT: ${env:DB_PORT}
    JWT_SECRET: ${env:JWT_SECRET}
  
functions:
  backend-sistema-asistencia:
    handler: src/app.handler
    name: backend-sistema-asistencia-${opt:stage, 'dev'}
    description: "Backend API for Sistema de Asistencia"
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000

package:
  individually: true
  patterns:
    - '!node_modules/aws-sdk/**'
    - '!node_modules/cypress/**'
    - '!node_modules/@cypress/**'
    - '!frontend/**'
    - '!__mocks__/**'
    - '!cypress/**'
    - '!.wwebjs_cache/**'
    - '!**/*.test.js'
    - '!**/__tests__/**'
    - 'src/**'
    - 'package.json'
    - '.env' 