service: plataforma-atrasos-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 256
  timeout: 30
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
  
functions:
  api:
    handler: src/app.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000

package:
  patterns:
    - '!node_modules/aws-sdk/**'
    - '!frontend/**'
    - '!__mocks__/**'
    - '!cypress/**'
    - '!.wwebjs_cache/**'
    - '!**/*.test.js'
    - '!**/__tests__/**' 