name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'Plataforma_Atrasos/**'
      - '!Plataforma_Atrasos/frontend/**'
      - '!Plataforma_Atrasos/cypress/**'
      - '!Plataforma_Atrasos/__mocks__/**'
      - '!**.md'

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: main
    defaults:
      run:
        working-directory: Plataforma_Atrasos
        shell: /usr/bin/bash -e {0}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Plataforma_Atrasos/package-lock.json

      - name: Install dependencies and serverless
        run: |
          # Install production dependencies
          npm ci --omit=dev --omit=optional
          
          # Install serverless and required plugins
          npm install -g serverless@3
          npm install --no-save serverless-offline serverless-dotenv-plugin @vendia/serverless-express

      - name: Deploy to AWS Lambda
        id: deploy
        run: serverless deploy --stage production --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          
      - name: Extract API endpoint
        id: extract-endpoint
        run: |
          # Get the API URL from API Gateway
          API_ID=$(aws apigateway get-rest-apis --region us-east-2 --query "items[?name=='plataforma-atrasos-backend-production'].id" --output text)
          
          if [ -n "$API_ID" ]; then
            API_URL="https://${API_ID}.execute-api.us-east-2.amazonaws.com/production"
            echo "API_URL=$API_URL" >> $GITHUB_ENV
            echo "API_URL=$API_URL" >> $GITHUB_OUTPUT
            echo "✅ API URL: $API_URL"
          else
            echo "⚠️ Could not determine API URL"
          fi 