name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'Plataforma_Atrasos/**'
      - '.github/workflows/deploy-lambda.yml'
      - '!Plataforma_Atrasos/frontend/**'
      - '!Plataforma_Atrasos/cypress/**'
      - '!Plataforma_Atrasos/__mocks__/**'
      - '!**.md'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: main
    outputs:
      api_url: ${{ steps.extract-endpoint.outputs.API_URL }}
      deployment_success: ${{ steps.deploy.outcome == 'success' }}
    defaults:
      run:
        working-directory: Plataforma_Atrasos
        shell: /usr/bin/bash -e {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Plataforma_Atrasos/package-lock.json

      - name: Create serverless packaging config
        run: |
          if ! grep -q "package:" serverless.yml; then
            echo -e "\n# Adding packaging configuration" >> serverless.yml
            echo "package:" >> serverless.yml
            echo "  individually: true" >> serverless.yml
            echo "  patterns:" >> serverless.yml
            echo "    - '!node_modules/aws-sdk/**'" >> serverless.yml
            echo "    - '!node_modules/**/aws-sdk/**'" >> serverless.yml
            echo "    - '!node_modules/**/*.md'" >> serverless.yml
            echo "    - '!node_modules/**/*.d.ts'" >> serverless.yml
            echo "    - '!node_modules/**/*.map'" >> serverless.yml
            echo "    - '!node_modules/**/LICENSE'" >> serverless.yml
            echo "    - '!node_modules/**/*.flow'" >> serverless.yml
            echo "    - '!node_modules/**/*.txt'" >> serverless.yml
            echo "    - '!node_modules/**/*.json'" >> serverless.yml
            echo "    - '!node_modules/**/test/**'" >> serverless.yml
            echo "    - 'node_modules/@serverless/**/test/**'" >> serverless.yml
            echo "    - '!node_modules/**/tests/**'" >> serverless.yml
            echo "    - 'node_modules/@serverless/**/tests/**'" >> serverless.yml
            echo "    - '!node_modules/**/examples/**'" >> serverless.yml
            echo "    - '!node_modules/**/docs/**'" >> serverless.yml
            echo "    - '!.git/**'" >> serverless.yml
            echo "    - '!.github/**'" >> serverless.yml
            echo "    - '!.vscode/**'" >> serverless.yml
            echo "    - '!docs/**'" >> serverless.yml
            echo "    - '!tests/**'" >> serverless.yml
            echo "    - '!.env*'" >> serverless.yml
            echo "    - '!*.log'" >> serverless.yml
            echo "    - '!cypress/**'" >> serverless.yml
            echo "    - '!__mocks__/**'" >> serverless.yml
            echo "    - '!frontend/**'" >> serverless.yml
            echo "    - '!node_modules/usb/**'" >> serverless.yml
            echo "    - '!node_modules/escpos*/**'" >> serverless.yml
            echo "    - '!node_modules/node-thermal-printer/**'" >> serverless.yml
            echo "    - '!node_modules/puppeteer*/**'" >> serverless.yml
            echo "    - '!node_modules/chromium*/**'" >> serverless.yml
          fi

      - name: Create .npmignore file
        run: |
          echo "# NPM ignore file to reduce package size" > .npmignore
          echo ".git/" >> .npmignore
          echo ".github/" >> .npmignore
          echo "node_modules/**/test/" >> .npmignore
          echo "!node_modules/@serverless/**/test/" >> .npmignore
          echo "node_modules/**/tests/" >> .npmignore
          echo "!node_modules/@serverless/**/tests/" >> .npmignore
          echo "node_modules/**/docs/" >> .npmignore
          echo "node_modules/**/examples/" >> .npmignore
          echo "*.log" >> .npmignore
          echo "*.md" >> .npmignore
          echo "cypress/" >> .npmignore
          echo "__mocks__/" >> .npmignore
          echo "frontend/" >> .npmignore
          echo "node_modules/usb/" >> .npmignore
          echo "node_modules/escpos*/" >> .npmignore
          echo "node_modules/node-thermal-printer/" >> .npmignore
          echo "node_modules/puppeteer*/" >> .npmignore
          echo "node_modules/chromium*/" >> .npmignore

      - name: Install dependencies and serverless
        run: |
          npm ci --omit=dev --omit=optional
          npm install -g serverless@3
          npm install --save serverless-offline serverless-dotenv-plugin @vendia/serverless-express whatsapp-web.js

      - name: Debug installed node_modules
        run: |
          if [ -d "node_modules/whatsapp-web.js" ]; then
            echo "✅ whatsapp-web.js encontrado en node_modules"
            ls -lh node_modules/whatsapp-web.js
          else
            echo "❌ whatsapp-web.js NO está en node_modules"
          fi

      - name: Optimize node_modules
        run: |
          find node_modules -type d -name "test" -o -name "tests" | grep -v "@serverless" | xargs rm -rf || true
          find node_modules -name "*.md" -o -name "*.d.ts" -o -name "*.map" -o -name "LICENSE" | xargs rm -rf || true
          rm -rf node_modules/usb node_modules/escpos* node_modules/node-thermal-printer node_modules/puppeteer* node_modules/chromium* || true

      - name: Modify serverless.yml to disable dashboard
        run: |
          if grep -q "org:" serverless.yml; then
            sed -i '/org:/d' serverless.yml
          fi
          if grep -q "app:" serverless.yml; then
            sed -i '/app:/d' serverless.yml
          fi
          echo -e "\norg: false" >> serverless.yml
          echo "app: false" >> serverless.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS Lambda
        id: deploy
        run: serverless deploy --stage production --region us-east-2 --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FRONTEND_URL: 'http://localhost:3000'
          FRONTEND_URL_PROD: ${{ secrets.AMPLIFY_FRONTEND_URL || 'https://main.dgv3bb9afnpc.amplifyapp.com' }}

      - name: Extract API endpoint
        id: extract-endpoint
        run: |
          API_ID=$(aws apigateway get-rest-apis --region us-east-2 --query "items[?name=='plataforma-atrasos-backend-production'].id" --output text)
          if [ -n "$API_ID" ]; then
            API_URL="https://${API_ID}.execute-api.us-east-2.amazonaws.com/production"
            echo "API_URL=$API_URL" >> $GITHUB_ENV
            echo "API_URL=$API_URL" >> $GITHUB_OUTPUT
            echo "✅ API URL: $API_URL"
          else
            echo "⚠️ Could not determine API URL"
          fi
