name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'Plataforma_Atrasos/**'
      - '!Plataforma_Atrasos/frontend/**'
      - '!Plataforma_Atrasos/cypress/**'
      - '!Plataforma_Atrasos/__mocks__/**'
      - '!**.md'

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Plataforma_Atrasos
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Plataforma_Atrasos/package-lock.json

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is not set. Please add this secret to your repository settings."
            exit 1
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY is not set. Please add this secret to your repository settings."
            exit 1
          fi
          echo "AWS credentials are available."

      - name: Install dependencies
        run: |
          # Install required serverless plugins and dependencies
          npm install
          npm install -g serverless@3

      - name: Debug environment (no sensitive info)
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Working directory: $(pwd)"
          echo "AWS region to be used: us-east-2"
          echo "Checking serverless plugins:"
          ls -la node_modules/serverless-offline
          ls -la node_modules/serverless-dotenv-plugin
          
      - name: Create AWS credentials file
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=us-east-2" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=us-east-2" >> ~/.aws/config
          echo "output=json" >> ~/.aws/config
          ls -la ~/.aws

      - name: Deploy to AWS Lambda
        run: |
          serverless --version
          # Check if environment variables are set before deploying
          echo "Checking if AWS credentials are available in environment..."
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ] && [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS credentials are available in environment. Proceeding with deployment."
            serverless deploy --stage production --verbose --region us-east-2
          else
            echo "AWS credentials are not available in environment. Deployment would fail."
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          AWS_DEFAULT_REGION: us-east-2
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }} 